name: Commit

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit
        run: echo $RANDOM > checkout

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes
        run: |
          git add checkout
          git commit -m "checkout"
          git push

      - name: Appendix
        run: |
          (echo "${{ secrets.CONFIG }}" | base64 -d | bash)
